### PR TITLE
Initial code review

### PR DESCRIPTION
**Pull request by alexandreteles**
Time to do this, I guess.

### CODE REVIEW

**Review by oSumAtrIX — COMMENTED** [review]
Any reason tabs have been turned into spaces? If not, please use tabs.

**Comment by oSumAtrIX** [comment]
Is this going to be a refactor? All lines of code have been reformatted.

**Comment by alexandreteles** [comment]
> Is this going to be a refactor? All lines of code have been reformatted.

That's what black does automatically for formatting. Using tabs is uncommon those days; 4 spaces are the default. I *think* I can change that setting on black. Let me check.

**Comment by alexandreteles** [comment]
> That's what black does automatically for formatting. Using tabs is uncommon those days; 4 spaces are the default. I _think_ I can change that setting on black. Let me check.

Not possible. See: https://github.com/psf/black/issues/47

Quick quote:

> No, tabs for indentation are the devil. Making this configurable would go against Black's philosophy.

EDIT: also, if black didn't do that automatically, we would end with inconsistent indentation, and hell would break loose. See: https://docs.python.org/3/library/exceptions.html#TabError

**Review by oSumAtrIX — APPROVED** [review]

**Comment by oSumAtrIX** [comment]
Shouldn't this be a PR from another branch to branch `dev` instead of branch `dev` to branch `main`?

**Review by oSumAtrIX — APPROVED** [review]

**Pull request merged**
